# Generated by Django 4.0.5 on 2022-07-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('office_phone', models.CharField(max_length=11, null=True)),
                ('mobile_phone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('top_image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallert_img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Image_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
