# Generated by Django 4.0.5 on 2022-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='office_phone',
            new_name='office_phone1',
        ),
        migrations.AddField(
            model_name='clinic',
            name='office_phone2',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
