# Generated by Django 4.0.5 on 2022-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0003_image_slider_description_top_image_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_image_slider',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
