# Generated by Django 4.0.5 on 2022-07-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0004_top_image_slider_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_image_slider',
            name='image_slider',
        ),
        migrations.AddField(
            model_name='image_slider',
            name='image_slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_doc.top_image_slider'),
        ),
    ]
