# Generated by Django 4.0.5 on 2022-07-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0005_remove_top_image_slider_image_slider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_slider',
            old_name='image_slider',
            new_name='top_image_slider',
        ),
    ]
