# Generated by Django 4.0.5 on 2022-07-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0006_rename_image_slider_image_slider_top_image_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_gallery_img', models.ImageField(upload_to='img')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='image_gallery',
            old_name='gallert_img',
            new_name='gallery_img',
        ),
        migrations.AddField(
            model_name='image_gallery',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image_gallery',
            name='op_gallery_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_doc.top_image_gallery'),
        ),
    ]
