# Generated by Django 4.0.5 on 2022-07-04 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0007_top_image_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
