# Generated by Django 4.0.5 on 2022-07-17 11:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0009_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(null=True)),
                ('answer', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
