# Generated by Django 4.0.5 on 2022-07-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0010_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_gallery',
            name='op_gallery_img',
        ),
        migrations.DeleteModel(
            name='Top_Image_gallery',
        ),
    ]
