# Generated by Django 4.0.4 on 2022-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0011_remove_image_gallery_op_gallery_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
